### ISSUE TITLE
Support for vim itself

### ISSUE THREAD

**Issue by sobrinho** [ayu-theme/ayu-vim#1]
Seems like there is rendering issues for vanilla vim (not neovim).

This is the preview: https://cloud.githubusercontent.com/assets/4568573/19404172/933ccdd2-9274-11e6-9178-ebdd31e17b9c.png

This is what I see using vim (almost no plugins):

<img width="1280" alt="screen shot 2016-10-17 at 18 16 50" src="https://cloud.githubusercontent.com/assets/26460/19453911/ea6a32ac-9495-11e6-8498-5d82d6f70cdd.png">

**Comment by dempfi** [comment]
As it's written in readme there is no support for vim yet. Only neovim with `termguicolors` running in true color terminals.

**Comment by sobrinho** [comment]
Hmmm! vim also supports that option which I have no idea about what is, I'll take a look at the vim documentation to see what is that.

Enabling it the vim rendered just like your preview.

There is something specific of neovim on the theme? What and why? Can we support it on vanilla vim?

**Comment by dempfi** [comment]
Basically that option enables rendering in true colors(16 million colors) instead of limited 16 or 256 colors. But true colors at first should be supported in terminal. iTerm since 2.9 beta supports true colors and neovim from the begging had support for true colors. Current version of ayu doesn't have any definitation of colors for 256 and 16 colored terminals.

**Comment by sobrinho** [comment]
Thanks!

This option is not specific of neovim, vim also have it and the theme is working correctly, I will make a pull request clearing the README about that.
