### ISSUE TITLE
Proposal for Maintainer role

### ISSUE THREAD

**Issue by saccarosium** [ayu-theme/ayu-vim#74]
Hi @dempfi  
I'm interested maintaining the repo. I've no prior experience as a maintainer but I wanna learn. It would be nice working also on other stuff like: alacritty and kitty themes, relaese docs for the main project etc. It would be possible?

**Comment by Luxed** [comment]
Look at issue #53. Many people would be interested in maintaining the project.
I currently have my own fork at [Luxed/ayu-vim](https://github.com/Luxed/ayu-vim).
I don't think the terminal themes would really fit into the vim repository. They would be nice to have in a "ayu-terminal" repository for example.
As for the documentation, I don't see what could be documented?
Theme works like any other theme, colors come from [ayu-colors](https://github.com/ayu-theme/ayu-colors) (or at least, it is true of my fork. And will be even more true once I finally merge my latest work which creates the colors file using the official npm package)

**Comment by saccarosium** [comment]
Yeah, I meant that it would be nice working at the project itself the colorscheme as a hole, like:
* For the terminals I meant separate projects in the ayu-theme repo;
* For the docs I meant docs like [the dracula](https://spec.draculatheme.com/) one and [the nord](https://www.nordtheme.com/docs/colors-and-palettes) one;
* I also have experience with emacs theming I can work on that also

**Comment by Luxed** [comment]
> For the terminals I meant separate projects in the ayu-theme repo

I've seen quite a few people wanting a theme for Kitty, Alacritty, Windows Terminal, Conemu, etc.
So I'm sure it would be appreciated. Unfortunately, since this repo is unmaintained, you should be asking somewhere else to add things to it. The "ayu-colors" would be a good entry point. But I believe you should make the repo yourself _then_ advertise it.

> For the docs I meant docs like [the dracula](https://spec.draculatheme.com/) one and [the nord](https://www.nordtheme.com/docs/colors-and-palettes) one

I see! That looks good, but once again, here is not the right place, I'd say "ayu-colors" would be even better for that. You could have a complete document in markdown explaining the theme and how it should work on all text editors.
Currently, my main issue with this theme is that it looks widely inconsistent between multiple editors (Sublime Text, VSCode and Vim are the ones I used). I'm sure documentation would help.

> I also have experience with emacs theming I can work on that also

I'm sure some would appreciate it!
I'm not an emacs user, so I never thought about it.
But if you are willing to maintain things that you don't use (I personally avoid maintaining things that I know I will not use), you could also make a theme for [kakoune](https://github.com/mawww/kakoune) and [micro](https://micro-editor.github.io/)

There's a lot of room for improvements with this theme and I'd be more than happy to have someone that tries to make it as good as possible!

**Comment by saccarosium** [comment]
> There's a lot of room for improvements with this theme and I'd be more than happy to have someone that tries to make it as good as possible!

Yeah, I feel the same. If you have ideas or need help I can help. 

For now I will try to make the alacrity and kitty ones, and I will try to contact the maintainer of the main repo.

Thanks for the help!
